### ISSUE TITLE
Welche Datei muss dort wie erstellt werden ?

### ISSUE THREAD

**Issue by kmuenke** [Eba-M/E3DC-Control#1]
Hallo Eberhard,

wie schon gesagt sehr schön hört sich das Program an, jedoch welche Datei muss auf den Raspberry ausgeführt werden. Ich vermute mal das du auch ein Linux am laufen hast ??? Das Makefile bringt nur Fehler ???

./Makefile: Zeile 4: ROOT_VALUE: Kommando nicht gefunden.
./Makefile: Zeile 4: all:: Kommando nicht gefunden.
./Makefile: Zeile 6: ROOT_VALUE: Kommando nicht gefunden.
./Makefile: Zeile 7: CXX: Kommando nicht gefunden.
./Makefile: Zeile 7: -O3: Kommando nicht gefunden.
./Makefile: Zeile 10: clean:: Kommando nicht gefunden.
./Makefile: Zeile 11: ROOT_VALUE: Kommando nicht gefunden.
./Makefile: Zeile 11: VECTOR: Kommando nicht gefunden.
./Makefile: Zeile 11: -rm: Kommando nicht gefunden.

mfg

Karsten

**Comment by kmuenke** [comment]
Ok habe es gefunden. Die Files werden mit make erstellt und das Programm wird mit E3DC-Control gestartet.
Danke

**Comment by Eba-M** [comment]
du musst im Verzeichnis E3DC-Control nur das Kommando 

make

eingeben.

Der c++ compiler sucht im aktuellen Verzeichnis nach dem 
Makefile u
und führt die Kommandos dort aus.

vorher muss erst mit dem Befehl

git clone  https://github.com/Eba-M/E3DC-Control.git 

der sourcecode auf den Raspi geladen werden.

lg

Eberhard

**Comment by kmuenke** [comment]
Ja Danke dir hat funktioniert. Mein E3DC sagt 

 

Connection failed

:5033cting to server 192.168.2.47

cannot be converted.47

Connection failed

 

Vermutlich muss ich das RSCP erst auf dem Speicher freischalten lassen so steht jedenfalls in der Anleitung ??

 

Mit freundlichen Grüßen

 

 

Karsten

 

Von: Eba-M [mailto:notifications@github.com] 
Gesendet: Montag, 20. August 2018 22:31
An: Eba-M/E3DC-Control <E3DC-Control@noreply.github.com>
Cc: kmuenke <kmuenke@gmx.de>; State change <state_change@noreply.github.com>
Betreff: Re: [Eba-M/E3DC-Control] Welche Datei muss dort wie erstellt werden ? (#1)

 

du musst im Verzeichnis E3DC-Control nur das Kommando 

make

eingeben.

Der c++ compiler sucht im aktuellen Verzeichnis nach dem 
Makefile u
und führt die Kommandos dort aus.

vorher muss erst mit dem Befehl

git clone https://github.com/Eba-M/E3DC-Control.git 

der sourcecode auf den Raspi geladen werden.

lg

Eberhard

**Comment by Eba-M** [comment]
ja du musst erst RSCP am S10 freischalten und Schlüssel vergeben.

gut Nacht

Eberhard

**Comment by kmuenke** [comment]
Guten Morgen ok call bei E3DC ist auf. Gibt es denn bei dem Programm eine Ausgabe ?? Oder werte die man ablesen kann ??
Mit freundlichen Grüßen
Karsten
		
		

		Outlook für iOS beziehen
	




On Mon, Aug 20, 2018 at 11:23 PM +0200, "Eba-M" <notifications@github.com> wrote:










ja du musst erst RSCP am S10 freischalten und Schlüssel vergeben.



gut Nacht



Eberhard
