### ISSUE TITLE
Fehler in der Anpassung von ladeende zwischen Tag/Nachtgleichen Herbst bis Frühling

### ISSUE THREAD

**Issue by ChrisKuBa** [Eba-M/E3DC-Control#13]
https://github.com/Eba-M/E3DC-Control/blob/1cc835cfe264cfc15186c7ae32ed5bf635e260cd/RscpExampleMain.cpp#L481

Hi Eberhard,

sollte hier nicht ladeende anstatt ladeende2 verwendet werden?

Ausgegangen von dem Standardwerte ladeende = 80 würde sich dieser um ca. 10% auf 90 zur Wintersonnenwende erhöhen, so wie du es mehrfach schon geschrieben hattest.
Ansonsten käme man mit der aktuellen Formel auf 96,5.

Persönlich würde ich auch eher folgendes schreiben:
```c++
fLadeende = (cos((ts->tm_yday+9)*2*3.14/365))*((100-fLadeende)/2)+fLadeende;
```
Damit ist klar, dass sich das nicht bis auf 100% erhöht, sondern nur bis auf die Mitte zwischen fladeende und 100%, bzw. um die Hälfte der Differenz.

Gruß Christian

**Comment by Eba-M** [comment]
Das ist schon so beabsichtigt. Hier folgt ladeende dem ladeende2
