### ISSUE TITLE
Complie warning....

### ISSUE THREAD

**Issue by n3rmix** [Eba-M/E3DC-Control#2]
RscpExampleMain.cpp:1224:85: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘std::vector<unsigned char>::size_type {aka unsigned int}’ [-Wformat=]
                 printf("Maximum buffer size exceeded %lu\n", vecDynamicBuffer.size());

It build the executable but at execution we get the following output:

Connecting to server 192.168.xxx.xxx:5033
Connected successfully

Request authentication

Request cyclic example data done
Connection closed by peer
mainloop beendetmainloop beendetConnecting to server 192.168.xxx.xxx:5033
Connected successfully

Any ideas?

**Comment by Eba-M** [comment]
Sieht doch schon mal gut aus, er verbindet sich mit dem System, die Verbindung wird aber vom E3DC (Peer) beendet.
Also mal am E3DC nachschauen ob Userid Password und Verschlüsselungscode stimmen.

lg

Eberhard
