### ISSUE TITLE
Compile Warning, die vermutlich einen Logikfehler signalisiert

### ISSUE THREAD

**Issue by stepkun** [Eba-M/E3DC-Control#20]
Hallo,

die folgende Warnmeldung ist vermutlich ein logischer Fehler:
SocketConnection.cpp: In function ‘int SocketConnect_noblock(const char*, int)’:
SocketConnection.cpp:167:23: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
Zeile  167 |             if (errno =! 36) {

Ich vermute mal stark, das der Vergleich 
if(errno != 36) 
lauten soll.

**Comment by Eba-M** [comment]
Danke für den Hinweis,

Ich habe diesen ganzen Teil so aus dem Beispielprogramm von E3DC übernommen.

Viele liebe Grüße!

Eberhard

**Comment by stepkun** [comment]
Dachte ich mir :-) Ich bin vor Jahren an den vielen Segmentation faults darin verzweifelt.

Ich habe noch etwas gefunden, was erst auffällt wenn man SocketConnection.h auch in SocketConnection.cpp einbindet:
SocketConnection.cpp:206:6: error: ambiguating new declaration of ‘long int SocketRecvData(int, unsigned char*, int)’
  206 | long SocketRecvData(int iSocket, unsigned char * ucBuffer, int iLength)
      |      ^~~~~~~~~~~~~~
Sollte wohl int sein - so stehts im Header und der return -Wert ist auch int

Herzlichen Dank für Deine Arbeit und viele Grüße
Stephan

**Comment by stepkun** [comment]
created a pull request
