### ISSUE TITLE
speichergroesse Parameter - Brutto oder Nettowert

### ISSUE THREAD

**Issue by skuske** [Eba-M/E3DC-Control#23]
Gebe ich für `speichergroesse` den Brutto- (Nenngröße) oder den Nettowert ein?

Habe drei Module á 3.25 kWh, also Brutto ca. 9.8 kWh, nutzbar aber dann nur 8.75 kWh lt. Spezifikation auf der E3/DC Webseite.

Vielen Dank für diesen tollen kleinen Helfer! Weiter so!

**Comment by Toskache** [comment]
> speichergroesse =        Speichergröße in kWh. Intern arbeitet das Programm immer nur mit dem % SoC das vom System geliefert wird. Der Parameter „speichergroesse“ dient aber der groben Abschätzung für die Ladegeschwindigkeit die zum Füllen des Speichers benötigt wird. Bei einem größeren Wert wird das laden zu Beginn etwas beschleunigen, bei kleinerem Wert verzögert. Man kann mit der Speichergröße die Ladung beeinflussen. Werden z.B 10kWh statt 13.8kWh eingetragen, wird er früher das Laden anfangen und anfänglich mit höherer Ladeleistung arbeiten und diese zum Ende hin stärker absenken.

**Comment by Eba-M** [comment]
Das spielt eigentlich so große keine Rolle, man kann auch bewusst mit der Batteriegröße spielen um ein bestimmtes Ladeverhalten zu erreichen. Gebe man einen zu großen Wert an, wird zunächst mit einer verhältnismassig großen Leistung geladen. Die Ladeleistung sinkt im Verlauf stark ab und das Ziel SoC wird korrekt erreicht.
Wird die Speichergröße zu klein angegeben, wird zunächst mit viel zu geringer Leistung geladen, dann wird die Ladeleistung kontinuierlich angehoben bis das Lade-SoC korrekt erreicht wird

**Comment by skuske** [comment]
Danke!
