### ISSUE TITLE
Tibber Integration

### ISSUE THREAD

**Issue by cko-skverlag** [Eba-M/E3DC-Control#24]
Hallo, ist es möglich den Stromversorger Tibber ähnlich wie awattar einzubinden? Danke!

**Comment by Eba-M** [comment]
Da ist kein Unterschied, da ja die Basis der  day-ahead market an der Epex ist. Da muss nichts angepasst werden.
Das die täglichen Daten von aWATTar genommen werden macht keinen Unterschied, wenn man korrekt sein möchte, müsste man direkt EPEX als Datenlieferant einbinden.

**Comment by Eba-M** [comment]
Es macht keinen Unterschied, ob Tibber oder aWATTar, aber nachdem ich zuerst aWATTar hatte, habe ich die Bezeichnungen danachgewählt.
aWATTar steht also als Vertretung für alle, auch zukünftige dynamische Börsentromtarife.

Eberhard
