### ISSUE TITLE
Wallbox: Ladestop

### ISSUE THREAD

**Issue by christianreiss** [Eba-M/E3DC-Control#25]
Hey,

kurze Frage: Weiss hier jemand, welchen RSCP Tag man senden muss um die aktuell laufende Ladung der Wallbox zu stoppen?

Grüße!

**Comment by Eba-M** [comment]
WBchar6[1] = 6;  // Laden von 6A aus
                            WBchar6[4] = 0; // Toggle aus
Über den Toggle wird die Wallbox ein und ausgeschaltet

Dann schickt man die Anfrage an das E3DC

    protocol.createContainerValue(&WBContainer, TAG_WB_REQ_DATA) ;
    // add index 0 to select first wallbox
    protocol.appendValue(&WBContainer, TAG_WB_INDEX,0);

    
    protocol.createContainerValue(&WB2Container, TAG_WB_REQ_SET_EXTERN);
    protocol.appendValue(&WB2Container, TAG_WB_EXTERN_DATA_LEN,6);
    protocol.appendValue(&WB2Container, TAG_WB_EXTERN_DATA,WBchar6,iWBLen);
