### ISSUE TITLE
Powerfaktor Parameter wird nicht richtig gezogen

### ISSUE THREAD

**Issue by MyGitIT** [Eba-M/E3DC-Control#31]
Hallo Eba, dein neuer Parameter Powerfaktor wird nicht richtig gezogen. Erst mit der Änderung in Zeile 491 von Powerfaktor zu powerfaktor funktioniert es.

Gruß

**Comment by Eba-M** [comment]
Der neue Parameter wird wie folgt belegt:
Powerfaktor = 2
