### ISSUE TITLE
Feature: Request: Schlechtwetter

### ISSUE THREAD

**Issue by merlin2539** [Eba-M/E3DC-Control#5]
Guten Morgen,
wenn schlechtes Wetter ist, dann schafft es leider die Software nicht entsprechend zu regeln. Hierbei wäre meine Idee, wenn der Wert der "PV" über einen bestimmten Schwellwert nicht kommt bis zu einer Uhrzeit, wird  der Speicher freigegeben für die Endladung? Das man am Abend auch den Speicher voll hat? 

Alternative wäre Solarwetter oder sowas über eine API anbinden und dadurch dann schauen ob man eine Regelung durchführen muss oder nicht

**Comment by Eba-M** [comment]
Hallo Markus,

du kannst die Ladeschwelle hochstehen, z.B. auf 70% 

Ladeschwelle = 70

den Ladekorridor runter, zwischen 500W und 900W, die 

untererLadekorridor = 500
obererLadekorridor = 900

ladeende = 85

jetzt wird er versuchen mit voller Ladeleistung bis 70% zu laden
bis Ende des Überwachungszeitraume der Überschussregelung wird dann bis auf 85% geladen. Der Überwachungszeitraum ergibt sich aus winterminimum und sommermaximum mittels einer cosinunsfunktion und sollte zum heutigen Zeitpunkt genau in der Mitte liegen.

hinzugekommen ist in der aktuellen Version ein neuer Parameter Uhrzeit für sommerladende. Damit gibt man für den Zeitpunkt der Sommersonnenwende an, wann das Laden beendet sein soll. Empfehlung 1-2h vor Sonnenuntergang bzw. Ende des Einspeiseüberschusses. Das tatsächliche Ladeende wird dann zwischen winterminimum und sommerladende über eine cosinusfuntion ermittelt. Bis zu diesem Zeitpunkt sollte der Speicher auf 93% geladen sein, anschließend wird weiter bis 100% geladen. Es soll damit vermieden werden, dass der Speicher zu lange bei 100% rumsteht, ohne wieder zu entladen werden. Wenn der Speicher im Sommer nicht mehr leer wird, kann man den Zeitpunkt auch noch nach weiter nach hinten schieben

sommerladeende = 18

Bitte bei den Zeitwerten beachten das mit GMT gearbeitet wird, d.h. MEZ Winterzeit - 1h (12:00 MEZ = 11:00 GMT)

lg

Eberhard

**Comment by merlin2539** [comment]
Hallo Eberhard,

danke für die Info, werde es mal versuchen und anschauen. Dachte eher an das Thema:
Ausschalten der Regelung bei "zuwenig Leistung komm". da der Flash im E3DC auch nur bestimmt oft beschrieben werden darf.(SChinung Hardware)

Solarwetter dachte ich sowas in der Art:
https://api.forecast.solar/estimate/watthours/48.506939/9.203804/15/0/9.90

=> 2019-03-27 18:52:00 29086.2 
(Erwahrter Wert = > Ladeschwelle wird nicht erreicht mit 70 => keine Regelung. API kann jeden Stundenwert

**Comment by Eba-M** [comment]
Hallo Markus,

vom Programm aus wird nichts auf den SSD geschrieben, es wird nur per TCP/IP mit dem E3DC kommuniziert.

lg

Eberhard

**Comment by merlin2539** [comment]
Hallo Eberhard,
wäre das nichts, das auch der Akku dann voll wird wenn nicht genügend Sonne kommt und das mit der normalen Regelung reichen würde.

z.B 

-für den Tag werden nur 20kwh kommen. Akku ist 15kwh, Hausverbrauch normal 8Kwh => keine Regelung bei Laden

-für den Tag werden nur 40kwh kommen. Akku ist 15kwh, Hausverbrauch normal 8Kwh => Regelung

Zusätzlich sieht man dort Stundenwerte:
Nur Vormittags kommt Sonne, dann bringt Laden nachmittag nichts mehr.

**Comment by kmuenke** [comment]
Hallo Eberhard,

 

frage komme ein wenig durcheinander mit der Sommer und Winterzeit. 

 

Muss ich da was umstellen. Jetzt ist es 11:28 Uhr. Auf der Console wird folgendes angezeigt.

 

Battery SOC 50.4 %  51.6 V  1.8 A

#0 is -1164.0 W -1906.0 W -2025.0 W  # -5095.0 W

& -5094.7 -5094.7 -5094.7 -5094.7 W

233.8 V 236.7 V 237.8 V

DC0 2801 W  348 V 8.05 A DC1 3791 W  445 V 8.52 A MinLoad: 981 0 GMT 13:43 ZG 107 E3DC Zeit: Wed Apr 24 09:29:23 2019

AVBatt   85.7 Discharge 3000 BattLoad 0 iLMStatus 1 Reserve 0.0%

 

Request cyclic example data done

^[y^[yEMS PV 6595 add 0 # 6595 BAT 90 home 1412 grid -5093 E3DC 0  # 1412

Battery SOC 50.4 %  51.6 V  1.8 A

#0 is -1164.0 W -1905.0 W -2024.0 W  # -5093.0 W

& -5094.6 -5094.6 -5094.6 -5094.6 W

233.8 V 236.7 V 237.8 V

DC0 2804 W  350 V 8.01 A DC1 3791 W  447 V 8.48 A MinLoad: 981 0 GMT 13:43 ZG 107 E3DC Zeit: Wed Apr 24 09:29:24 2019

AVBatt   85.9 Discharge 3000 BattLoad 0 iLMStatus 1 Reserve 0.0%

 

Request cyclic example data done

EMS PV 6582 add 0 # 6582 BAT 90 home 1407 grid -5085 E3DC 0  # 1407

Battery SOC 50.4 %  51.6 V  1.8 A

#0 is -1158.0 W -1904.0 W -2023.0 W  # -5085.0 W

& -5094.2 -5094.2 -5094.2 -5094.2 W

233.8 V 236.7 V 237.8 V

DC0 2795 W  352 V 7.94 A DC1 3787 W  445 V 8.51 A MinLoad: 981 0 GMT 13:43 ZG 107 E3DC Zeit: Wed Apr 24 09:29:25 2019

AVBatt   86.1 Discharge 3000 BattLoad 0 iLMStatus 1 Reserve 0.0%

 

Da stimmt doch was nicht oder.

 

Mfg

 

Karsten

 

Von: Eberhard Mayer [mailto:notifications@github.com] 
Gesendet: Mittwoch, 27. März 2019 20:50
An: Eba-M/E3DC-Control <E3DC-Control@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Eba-M/E3DC-Control] Feature: Request: Schlechtwetter (#5)

 

Hallo Markus,

vom Programm aus wird nichts auf den SSD geschrieben, es wird nur per TCP/IP mit dem E3DC kommuniziert.

lg

Eberhard

**Comment by Eba-M** [comment]
Hallo Markus 

die Zeitangabe hinter GMT zeigt die berechnete Uhrzeit an bis zu der mit Überschuss zu rechnen ist.
Die E3DC Zeit ist die aktuelle Zeit in GMT 

lg

Eberhard 

Gesendet mit der GMX iPhone App

Am 24.04.19 um 11:30 schrieb kmuenke

**Comment by kmuenke** [comment]
Ok danke für die Info. Dann noch ein Frage zur Ladeleistung warum ist die jetzt auf 1500 begrenzt wenn die Max Ladeleistung auf 3000 Watt steht ??

 



 

Mfg

 

Karsten

 

Von: Eberhard Mayer [mailto:notifications@github.com] 
Gesendet: Mittwoch, 24. April 2019 19:58
An: Eba-M/E3DC-Control <E3DC-Control@noreply.github.com>
Cc: kmuenke <kmuenke@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Eba-M/E3DC-Control] Feature: Request: Schlechtwetter (#5)

 

Hallo Markus 

die Zeitangabe hinter GMT zeigt die berechnete Uhrzeit an bis zu der mit Überschuss zu rechnen ist.
Die E3DC Zeit ist die aktuelle Zeit in GMT 

lg

Eberhard 

Gesendet mit der GMX iPhone App

Am 24.04.19 um 11:30 schrieb kmuenke

**Comment by Eba-M** [comment]
> Guten Morgen,
> wenn schlechtes Wetter ist, dann schafft es leider die Software nicht entsprechend zu regeln. Hierbei wäre meine Idee, wenn der Wert der "PV" über einen bestimmten Schwellwert nicht kommt bis zu einer Uhrzeit, wird der Speicher freigegeben für die Endladung? Das man am Abend auch den Speicher voll hat?
> 
> Alternative wäre Solarwetter oder sowas über eine API anbinden und dadurch dann schauen ob man eine Regelung durchführen muss oder nicht

In der neuesten Version muss man das Programm nicht mehr beenden, wenn man an der e3dc.config.txt etwas ändern möchte. Bei Schlechtwetter den parameter ladeschwell = 100 setzen und es wird geladen, was geht. Da zurücksetzen für schönes Wetter nicht vergessen.
Aber eigentlich nicht nötig, wenn man die Parameter ladeende und sommermaximum sowie ladeende2 und sommerladeende sinnvoll besetzt. Im Sommer hat man oft das Problem, dass der Speicher nicht leer wird. Können wir also dem Speicher bei Schlechtwetter, dass er nur bis auf 90% geladen wird. Dann muss man ihn am Morgen mit unload nicht entladen, um Platz für die Überschussregelung zu schaffen.
