### ISSUE TITLE
Regelung geht nicht?

### ISSUE THREAD

**Issue by Micha70** [Eba-M/E3DC-Control#8]
Hallo Eberhard,

ich habe die Steuerung seit über einem halben Jahr in Betrieb und es hat alles prima funktioniert.

Letzte Woche habe ich ein Update auf die neueste Version gemacht, es aber bisher noch nicht zum Laufen bekommen. Die Regelung scheint nicht mehr zu funktionieren. Der Speicher wird morgens voll geladen. Mit der alten Regelung war bei 55% Schluss, danach nur Überschussladung bis dann am Nachmittag das Laden frei gegeben wurde. Muss man an den Parametern noch was modifieren? Anbei meine eingestellten Parameter und die Ausgabe von der Konsole clipboard.txt.
[clipboard.txt](https://github.com/Eba-M/E3DC-Control/files/3124151/clipboard.txt)

Parameter aus e3dc.config.txt:
wurzelzaehler = 6
ladeschwelle = 55
ladeende = 90
untererLadekorridor = 500
obererLadekorridor = 800
minimumLadeleistung = 300
maximumLadeleistung = 1500
speichergroesse = 6.9
winterminimum = 10.5
sommermaximum = 14.5
einspeiselimit = 3.9

Interessant ist auch, dass immer wieder die Statusausgaben kommen:

"POWER_LIMITS_USED
MAX_CHARGE_POWER 1500 W
MAX_DISCHARGE_POWER 1500 W
DISCHARGE_START_POWER 65 W
POWERSAVE_ENABLED"

Das war in der Version, die ich vor einem halben Jahr runtergeladen hatte nicht so ...

So wie ich gesehen habe hat Karsten wohl ein ähnliches Problem...
https://www.photovoltaikforum.com/thread/125497-e3dc-%C3%BCberschusssteuerung-per-rscp-und-raspberry-pi/?postID=1760088#post1760088

Vielen Dank schon mal für deine Unterstützung.

MichaW

**Comment by Eba-M** [comment]
ladeende = 75     
winterminimum = 11
sommermaximum = 14
sommerladeende = 18.5

in der aktuellen Version ist noch der Parameter "sommerladeende" hinzugekommen.
In meinem Beispiel wird zweistufig geladen. Zuerst wird  "sommermaximum" (16:00 Sommerzeit) bis auf 75% geladen, anschließend bis auf 93% bis "sommerladeende" (20:30 Sommerzeit) mit anschließender Ladefreigabe auf 100%. Damit wird verhindert, dass der Speicher zu lange mit hohem SoC herumsteht.
Zudem bleibt genügend freie Kapazität zwischen den 75% und 93% für die Aufnahme des Überschussstromes.

**Comment by Micha70** [comment]
Hmm, verstehe ich trotzdem nicht ganz ... Auch wenn der Parameter sommerladeende nicht in e3dc.config.txt gesetzt ist, wird der default  Wert (#define SOMMERLADEENDE  18.5) verwendet. 
Aber warum wird das Laden nicht am Morgen nach erreichen der Ladeschwelle (55%) beendet?

**Comment by Eba-M** [comment]
bei
ladeschwelle = 55
ladeende = 90
sommermaximum = 14.5

der Speicher sollte, nachdem erst einmal die 55% SoC erreicht wurden, gleichmäßig bis spätestens 16:30 (MEZ Sommerzeit) auf 90% geladen werden. Bei mir wäre das zur Zeit bis 15:18 (MEZ Sommerzeit)
Die Statusangaben werden immer beim Starten des Programms angezeigt.
Wie läßt du das Programm dann laufen? Ich benutze Screen, um mich jederzeit per ssh mit dem Raspi verbinden zu können und die Ausgaben des Programms ansehen zu können.
Wenn du das Programm nur im Terminalfenster startest, wird es mit dem Schließen des Terminalfensters auch wieder beendet.
Einen Auszug der Ausgaben nach Erreichen der 55% SoC, wenn in den Regelmodus gewechselt wurde, wäre mir hilfreich.

**Comment by Micha70** [comment]
Das Programm läuft unter Screen und wird beim Booten des Raspi automatisch mit gestartet. Mit Screen -r kann ich dann jederzeit reinschauen. Wie geschrieben läuft es seit mehr als einem halben Jahr mit der alten Variante. Ein Logfile hatte ich meinem ersten Post bereits angehängt (clipboard.txt) . Man sieht, dass trotz SOC 60.8% mit voller Leistung weiter geladen wird...

**Comment by Eba-M** [comment]
Besteht das Problem weiterhin? in der Debugausgabe sehe ich, das was an dem E3DC geschickt wird.
Möglicherweise wird das von E3DC nicht akzeptiert. Aber warum nicht!

**Comment by Micha70** [comment]
Hallo Eba,
ich habe vor ca. zwei Wochen auf die letzte Version von dir upgedatet. Seitdem funktioniert es wieder. Ich schliesse den Issue.

**Comment by Micha70** [comment]
Scheinbar mit dem Commit 7. Mai gelöst.
